---

- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - "customers/{{ customer }}/vars.yml"
  vars:
  tasks:
    - name: Configure Antivirus Policy Settings
      fortios_antivirus_profile:
        vdom: "{{ vdom }}"
        state: present
        antivirus_profile: 
          name: "HTMS Antivirus"
          comment: "High Touch generated Antivirus"
          analytics_db: "enable"
          av_block_log: "enable"
          av_virus_log: "enable"
          http:
            av_scan: "block"
            outbreak_prevention: "block"
          ftp:
            av_scan: "block"
            outbreak_prevention: "block"
          imap:
            av_scan: "block"
            outbreak_prevention: "block"
          pop3:
            av_scan: "block"
            outbreak_prevention: "block"
            executables: "virus"
          smtp:
            av_scan: "block"
            outbreak_prevention: "block"
          cifs:
            av_scan: "block"
            outbreak_prevention: "block"
          outbreak_prevention_archive_scan: "disable"
          external_blocklist_enable_all: "enable"