- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
  tasks:
    - name: Create Single Sign-On for Azure SAML Authentication
      fortios_user_saml:
        vdom: "{{ vdom }}"
        state: present
        access_token: "{{ fortios_access_token }}" #if you prefer access token based authentication, add this line.
        user_saml:
          name: "Microsoft Azure SAML"
          cert: "{{ azure_local_certname }}"
          entity_id: "https://{{ vpn_domain }}/remote/saml/metadata"
          single_sign_on_url: "https://{{ vpn_domain }}/remote/saml/login"
          single_logout_url: "https://{{ vpn_domain }}/remote/saml/logout"
          idp_entity_id: "https://sts.windows.net/{{ azure_tenant_id }}/"
          idp_single_sign_on_url: "https://login.microsoftonline.com/{{ azure_tenant_id }}/saml2"
          idp_single_logout_url: "https://login.microsoftonline.com/{{ azure_tenant_id }}/saml2"
          idp_cert: "{{ azure_remote_certname }}"
          user_name: "user"
          group_name: "groups"
          digest_method: "sha1"
      when: sslvpn_auth_type == "saml"

    - name: Greate User Group for SSLVPN Authentication
      fortios_user_group:
        vdom: "{{ vdom }}"
        state: present
        access_token: "{{ fortios_access_token }}" #if you prefer access token based authentication, add this line.
        user_group:
          name: "SSLVPN_Users"
          member:
           - 
            name: "Microsoft Azure SAML"
      when: sslvpn_auth_type == "saml"