---

## Work in progress, there may be a bug. I have not found a way to get this to configure a port successfully.

- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - "customers/{{ customer }}/vars.yml"
  vars:
  tasks:
    - name: Configure ports with managed APs
      fortios_switch_controller_managed_switch:
        vdom: "{{ vdom }}"
        state: present
        access_token: "{{ fortios_access_token }}"
        switch_controller_managed_switch:
          name: ""
          ports:
            -
          #     switch_id: "S108FFTV21022363"
          #     access_mode: "normal"
              port_number: 1
              allowed_vlans_all: "enable"
              port_name: "port 1"
          #     allowed_vlans:
          #      - vlan_name: "all"
          #     # edge_port: "disable"
          #     poe_capable: 1
          #     speed: auto
          #     # status: "up"
          #     type: "physical"
          #     export_to: "root"
          #     untagged_vlans:
          #       - vlan_name: "quarantine"
          #     vlan: "Management"
          switch_id: ""

            # edit "port7"
            #     set poe-capable 1
            #     set vlan "Management"
            #     set allowed-vlans-all enable
            #     set untagged-vlans "quarantine"
            #     set export-to "root"
            #     set mac-addr 84:39:8f:c0:a9:17
            # next
