---
#################################################
## Test code to be used in production scripts. ##
#################################################

- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  vars_files:
    - "customers/{{ customer }}/vars.yml"
  vars:
  tasks:
    - name: Gather firewall policy information
      fortios_configuration_fact:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        formatters:
          - name
          - policyid
        selector: 'firewall_policy'
        filters:
          - name=="SSLVPN"
      register: policies

    - debug:
        msg: "{{ policies.meta.results }}"
        #msg: "{{ ( policies.meta.results | sort(attribute='policyid') | last).policyid +1 }}"