---
#################################################
## Test code to be used in production scripts. ##
#################################################

- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  tasks:
    - name: Gather firewall policy information
      fortios_configuration_fact:
        vdom: "{{ vdom }}"
        selector: 'firewall_address'
        filters:
          - name=="SSLVPN_TUNNEL_ADDR1"
      register: address_object

    - debug:
        msg: "{{ address_object.meta.results.0['start-ip'] }}"
        #msg: "{{ ( policies.meta.results | sort(attribute='policyid') | last).policyid +1 }}"