---

- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - "customers/{{ customer }}/vars.yml"
  vars:
  tasks:
    - name: fact gathering with filters
      fortios_configuration_fact:
        vdom: "{{ vdom }}"
        selector: 'system_interface'