---

## This files was for me to test reading the hostname from the inventory for future use.

- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 10443
  tasks:
  #  - name: Configure global attributes.
  #    fortios_system_global:
  #       vdom:  "{{ vdom }}"
  #       access_token: "{{ fortios_access_token }}"
  #       system_global:
  #           hostname: "{{ inventory_hostname }}"
     - name: Test
       ansible.builtin.debug:
         msg: "{{ inventory_hostname }}"