---

- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: yes
  vars_files:
    - "customers/{{ customer }}/vars.yml"
  vars:
  tasks:
    - name: Configure the Internet Outbound policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        firewall_policy:
          action: accept
          application_list: "HTMS Application"
          av_profile: "HTMS Antivirus"
          dstaddr: 
           -  name: all
          dstintf:
           - name: virtual-wan-link
          ips_sensor: "HTMS Protect Client"
          logtraffic_start: enable
          logtraffic: all
          name: "Internet Outbound"
          nat: enable
          policyid: 1
          schedule: always
          service:
           - name: ALL
          srcaddr:
           - name: all
          srcintf:
           - name: any
          ssl_ssh_profile: certificate-inspection
          status: enable
          utm_status: enable
          webfilter_profile: "HTMS Webfilter"