---

- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no 
  vars_files:
    - "customers/{{ customer }}/vars.yml"
  vars:
  tasks:
    - name: Configure IPS-Sensor
      fortios_ips_sensor:
        vdom: "{{ vdom }}"
        state: present
        ips_sensor:
          name: "HTMS Protect Client"
          comment: "High Touch generated policy"
          block_malicious_url: "enable"
          entries:
           -
            id: "1"
            location: "client"
          scan_botnet_connections: "block"