---

## Work in progress

- hosts: 
    - fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - vars.yml
    - ipsec_vars.yml
  vars:
  tasks:
  - name: Register Allowed URLs from CSV file
    read_csv:
      path: ./files/vpn_addresses.csv
    register: addresses

  - name: Configure address objects for vpn
    fortios_firewall_address:
      vdom: "{{ vdom }}"
      state: present
      access_token: "{{ fortios_access_token }}"
      firewall_address:
        name: "{{ item.name }}"
        type: "ipmask"
        subnet: "{{ item.subnet }}"
        allow_routing: "enable"
    loop: "{{ addresses.list }}"
