- hosts: 
  - localhost
  vars_files:
    - ipsec_vars.yml
  vars:
  tasks:
  - name: Register addrresses to append address to group
    read_csv:
      path: ./files/vpn_addresses.csv
    register: addresses

  - name: Prepare The Shell Script to append addresses to group
    raw: |
           cat > {{script_path }} << EOF_OUTER
           # /bin/bash
           # Please make sure tool sshpass is installed. e.g. on Debian/Ubuntu, apt-get install sshpass.
           # Optionally you can pass some parameters.
           # The character `a` at second line below is to avoid post-login-banner barrier.
           sshpass -p '{{ fgt_pass }}' ssh -o StrictHostKeyChecking=no {{ fgt_user }}@{{ fgt_host }} <<EOF
           a
           # ====================== Edit Your Commands Below =============================================
           config firewall addrgrp
           edit '\$1'
           append member '\$2'
           set allow-routing 'enable'
           end
           # ==============================================================================================
           EOF
           EOF_OUTER


  - name: Append address to the group for Site 1
    raw: |
           chmod +x {{ script_path }} && {{ script_path }} '{{ site1_name }}_VPN_{{ item.site1 }}' '{{ item.name }}'
    args:
      executable: /bin/bash
    with_items: "{{ addresses.list }}"
    