---

- hosts: 
  - localhost
  vars:
  tasks:
  - name: Create private key (RSA, 4096 bits)
    community.crypto.openssl_privatekey:
      path: /workspaces/projects/ansible/ansible-playbooks/fortios/certificates/certificate.key

  - name: Create certificate signing request (CSR) for self-signed certificate
    community.crypto.openssl_csr_pipe:
      privatekey_path: /workspaces/projects/ansible/ansible-playbooks/fortios/certificates/certificate.key
      common_name: your_common_name
      organization_name: your_org_name
    register: csr

  - name: Create self-signed certificate from CSR
    community.crypto.x509_certificate:
      path: /workspaces/projects/ansible/ansible-playbooks/fortios/certificates/certificate.pem
      csr_content: "{{ csr.csr }}"
      privatekey_path: /workspaces/projects/ansible/ansible-playbooks/fortios/certificates/certificate.key
      provider: selfsigned