- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
  tasks:
    - name: Remove SIP ALG Session-Helper
      fortios_system_session_helper:
        vdom: "{{ vdom }}"
        state: absent
        access_token: "{{ fortios_access_token }}" #if you prefer access token based authentication, add this line.
        system_session_helper:
          id: "13"
                  