---

- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - "customers/{{ customer }}/vars.yml"
  vars:
  tasks:
  
    - name: Upgrade Fortigate 200F firmware
      fortios_monitor:
        vdom: "root"
        selector: 'upgrade.system.firmware'
        params:
          source: "upload"
          filename: "FGT_200F-v7.4.0.F-build2360-FORTINET.out"
          file_content: "{{ lookup( 'file', 'FGT_200F-v7.4.0.F-build2360-FORTINET.out') | string | b64encode }}"
      when:
        - model == "200F"
      vars:
      ansible_command_timeout: 1800

    - name: Upgrade Fortigate 60F firmware
      fortios_monitor:
        vdom: "root"
        selector: 'upgrade.system.firmware'
        params:
          source: "upload"
          filename: "FGT_VM64-v6-build1828-FORTINET.out"
          file_content: "{{ lookup( 'file', 'FGT_60F-v7.4.0.F-build2360-FORTINET.out') | string | b64encode }}"
      when:
        - model == "60F"
      vars:
      ansible_command_timeout: 1800