---
# I have upgrade my common to practice to use zones in policies instead of interfaces. I will update this code in the future to include zones.

- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: yes
  vars_files:
    - vars.yml
  vars:
  tasks:
    - name: Configure Data Inter-VLAN traffic firewall policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        access_token: "{{ fortios_access_token }}"
        firewall_policy:
          action: accept
          dstaddr: 
           - name: "Wireless address"
           - name: "Security address"
           - name: "Management address"
          dstintf:
           - name: "Wireless"
           - name: "Security"
           - name: "Management"
          logtraffic_start: enable
          logtraffic: all
          name: "Data Inter-VLAN traffic"
          nat: disable
          policyid: 70
          schedule: always
          service:
           - name: ALL
          srcaddr:
           - name: "Data address"
          srcintf:
           - name: "Data"
          ssl_ssh_profile: no-inspection
          status: enable
          utm_status: enable

    - name: Configure Security Inter-VLAN traffic firewall policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        access_token: "{{ fortios_access_token }}"
        firewall_policy:
          action: accept
          dstaddr: 
           - name: "Data address"
           - name: "Wireless address"
           - name: "Management address"
          dstintf:
           - name: "Data"
           - name: "Wireless"
           - name: "Management"
          logtraffic_start: enable
          logtraffic: all
          name: "Security Inter-VLAN traffic"
          nat: disable
          policyid: 71
          schedule: always
          service:
           - name: ALL
          srcaddr:
           - name: "Security address"
          srcintf:
           - name: "Security"
          ssl_ssh_profile: no-inspection
          status: enable
          utm_status: enable
    
    - name: Configure Wireless Inter-VLAN traffic firewall policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        access_token: "{{ fortios_access_token }}"
        firewall_policy:
          action: accept
          dstaddr: 
           - name: "Security address"
           - name: "Data address"
           - name: "Management address"
          dstintf:
           - name: "Security"
           - name: "Data"
           - name: "Management"
          logtraffic_start: enable
          logtraffic: all
          name: "Wireless Inter-VLAN traffic"
          nat: disable
          policyid: 72
          schedule: always
          service:
           - name: ALL
          srcaddr:
           - name: "Wireless address"
          srcintf:
           - name: "Wireless"
          ssl_ssh_profile: no-inspection
          status: enable
          utm_status: enable

    - name: Configure Management Inter-VLAN traffic firewall policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        access_token: "{{ fortios_access_token }}"
        firewall_policy:
          action: accept
          dstaddr: 
           - name: "Security address"
           - name: "Wireless address"
           - name: "Data address"
          dstintf:
           - name: "Security"
           - name: "Wireless"
           - name: "Data"
          logtraffic_start: enable
          logtraffic: all
          name: "Wireless Inter-VLAN traffic"
          nat: disable
          policyid: 72
          schedule: always
          service:
           - name: ALL
          srcaddr:
           - name: "Management address"
          srcintf:
           - name: "Management"
          ssl_ssh_profile: no-inspection
          status: enable
          utm_status: enable
