## One time scipt run for greating zones. Planned common integration.


- hosts: 
  - localhost
  vars_files:
    - ssh_vars.yml
    - interface_settings.yml
  vars:
  tasks:

  - name: Prepare The Shell Script to append addresses to group
    raw: |
           cat > {{ script_path }} << EOF_OUTER
           # /bin/bash
           # Please make sure tool sshpass is installed. e.g. on Debian/Ubuntu, apt-get install sshpass.
           # Optionally you can pass some parameters.
           # The character `a` at second line below is to avoid post-login-banner barrier.
           sshpass -p '{{ fgt_pass }}' ssh -o StrictHostKeyChecking=no {{ fgt_user }}@{{ fgt_host }} <<EOF
           a
           # ====================== Edit Your Commands Below =============================================
           config system zones
           edit 'LAN'
           append interface '\$1'
           end
           # ==============================================================================================
           EOF
           EOF_OUTER


  - name: Append address to the group for Site 1
    raw: |
           chmod +x {{ script_path }} && {{ script_path }} '{{ item.name }}'
    args:
      executable: /bin/bash
    with_items: "{{ interfaces }}"
    