---
- name: Change IOS VLAN 
  hosts: switches
  gather_facts: no
  connection: network_cli

  tasks:
  - name: Gather Layer 2 interface information
    register: switch_ports
    cisco.ios.ios_facts:
      gather_subset: min
      gather_network_resources: l2_interfaces

  - name: Backup the running-config
    cisco.ios.ios_config:
      backup: yes

  - name: Configure Layer 2 interfaces  
    cisco.ios.ios_config:
      lines: 
        - switchport access vlan 96
      parents: interface {{ item.name }}
      save_when: changed
    loop: "{{ ansible_network_resources.l2_interfaces }}"
    when:
      - item.access is defined
      - item.mode == 'access'
      - item.access.vlan == 20

#  - name: Post Backup
#    cisco.ios.ios_config:
#      backup: yes