---
- name: Gather IOS Model & Serial Numbers
  hosts: switches
  gather_facts: no
  connection: network_cli

  tasks: 
    - name: Gather facts
      ios_facts:
        gather_subset: all

    - name: Display Model & Serial Number
      debug:
        msg: "Model Number of {{ ansible_net_hostname }} is {{ ansible_net_model }} and serial number is {{ ansible_net_serialnum }}" 
