---
- name: Meraki AP port config
  hosts: switches
  gather_facts: no
  connection: network_cli

  tasks:
  - name: Collect Neighbors
    register: switch_interfaces
    cisco.ios.ios_facts:
      gather_subset: all
      gather_network_resources:
        - all

  - name: Display interfaces
    local_action: copy content={{ switch_interfaces | to_nice_json }} dest=./ansible_facts.json

