- name: Add Vlan to IOS switches
  hosts: switches
  connection: network_cli
  vars:
    input: "{{ lookup('file', 'ios_vlans.json') | from_json }}"
    supernet: "10.10"
  tasks:
  - name: Register JSON as fact
    set_fact:
      vlans: "{{ input.vlans.vlan }}"

  - name: Add VLANs
    cisco.ios.ios_config:
      lines: 
        - "vlan {{ item.vlan_id }}"
        - "name {{ item.vlan_name }}"
    with_items: "{{ vlans }}"

  - name: Add VLAN interface
    cisco.ios.ios_l3_interfaces:
      config:
      - name: "Vlan{{ item.vlan_id }}"
        ipv4:
        - address: "{{supernet}}.{{ item.vlan_id }}.1/24"
      state: merged
    with_items: "{{ vlans }}"