---
- name: Meraki AP port config
  hosts: switches
  gather_facts: no
  connection: network_cli
    
  tasks:
  - name: Collect Neighbors
    register: neighbor_switches
    cisco.ios.ios_facts:
      gather_subset: interfaces

  - name: Backup before making changes
    cisco.ios.ios_config:
      backup: yes

  - name: Update port configuration
    cisco.ios.ios_config:
      backup: no
      lines:
        - description Connected to {{ item.value[0].host }} on port {{ item.value[0].port}}
      parents: interface {{ item.key }}
      save_when: changed
    with_dict: "{{ neighbor_switches.ansible_facts.ansible_net_neighbors }}"
    when: ansible_network_os == 'ios'

  - name: Post Backup
    cisco.ios.ios_config:
      backup: yes