---
- name: Fortigate Configuration
  hosts: fortigates
  collections:
  - fortinet.fortios
  connection: httpapi
  gather_facts: False
  roles:
    - role: common
    - role: interfaces
      when:
        - interfaces is defined 
        - interfaces = true
    - role: clientvpn
      when:
        - clientvpn is defined 
        - clientvpn = true