---
- name: Create Single Sign-On for Azure SAML Authentication
  fortios_user_saml:
    vdom: "{{ vdom }}"
    state: present
    user_saml:
      name: "Entra-ID-SAML"
      cert: "{{ azure_local_certname }}"
      entity_id: "https://{{ vpn_domain }}/remote/saml/metadata"
      single_sign_on_url: "https://{{ vpn_domain }}/remote/saml/login"
      single_logout_url: "https://{{ vpn_domain }}/remote/saml/logout"
      idp_entity_id: "https://sts.windows.net/{{ azure_tenant_id }}/"
      idp_single_sign_on_url: "https://login.microsoftonline.com/{{ azure_tenant_id }}/saml2"
      idp_single_logout_url: "https://login.microsoftonline.com/{{ azure_tenant_id }}/saml2"
      idp_cert: "{{ azure_remote_certname }}"
      user_name: "username"
      group_name: "group"
      digest_method: "sha1"
  when:
    - sslvpn_auth_type is defined 
    - sslvpn_auth_type == "saml"

- name: Greate User Group for SSLVPN Authentication
  fortios_user_group:
    vdom: "{{ vdom }}"
    state: present
    user_group:
      name: "SSLVPN_Users"
      member:
        - 
        name: "Entra-ID-SAML"
  when:
    - sslvpn_auth_type is defined 
    - sslvpn_auth_type == "saml"