- name: Configure Webfilter Policy Settings
  fortios_application_list:
    vdom: "{{ vdom }}"
    state: present
    # access_token: "{{ fortios_access_token }}"
    application_list:
      name: "HTMS Application"
      comment: "High Touch generated policy"
      other_application_log: "enable"
      unknown_application_log: "enable"