- name: Configure Fortigate System Settings
  fortios_system_settings:
    vdom: "{{ vdom }}"
    access_token: "{{ fortios_access_token }}"
    system_settings:
      gui_multicast_policy: enable
      gui_multiple_interface_policy: enable
      gui_switch_controller: enable
      gui_wireless_controller: enable
      gui_dos_policy: enable
