- name: Configure Fortigate System Global Settings
  fortios_system_global:
    vdom: "{{ vdom }}"
    # access_token: "{{ fortios_access_token }}"
    system_global:
      admin_console_timeout: 120
      admintimeout: 30
      gui_certificates: enable
      gui_theme: mariner
      hostname: "{{ inventory_hostname }}"
      switch_controller: enable
      timezone: "America/Chicago"
      remoteauthtimeout: 120