- name: Create Allowed Category
  fortios_webfilter_ftgd_local_cat:
    vdom: "{{ vdom }}"
    state: present
    # access_token: "{{ fortios_access_token }}"
    webfilter_ftgd_local_cat:
      desc: "Allowed"
      id: 190
      status: "enable"
      
- name: Create Blocked Category
  fortios_webfilter_ftgd_local_cat:
    vdom: "{{ vdom }}"
    state: present
    # access_token: "{{ fortios_access_token }}"
    webfilter_ftgd_local_cat:
      desc: "Blocked"
      id: 191
      status: "enable"

- name: Add Allowed URLs to Custom1 Web Rating Overrides
  fortios_webfilter_ftgd_local_rating:
    vdom: "{{ vdom }}"
    state: present
    # access_token: "{{ fortios_access_token }}"
    webfilter_ftgd_local_rating:
      rating: "190"
      status: "enable"
      url: "{{ item }}"
  loop: "{{ allowed_urls }}"
  when: allowed_urls is defined

- name: Add Blocked URLs to Custom1 Web Rating Overrides
  fortios_webfilter_ftgd_local_rating:
    vdom: "{{ vdom }}"
    state: present
    # access_token: "{{ fortios_access_token }}"
    webfilter_ftgd_local_rating:
      rating: "191"
      status: "enable"
      url: "{{ item }}"
  loop: "{{ blocked_urls }}"
  when: blocked_urls is defined

- name: Configure Webfilter Policy Settings
  fortios_webfilter_profile:
    vdom: "{{ vdom }}"
    state: present
    # access_token: "{{ fortios_access_token }}"
    webfilter_profile:
      name: "HTMS Webfilter"
      comment: "High Touch generated policy"
      web:
        blocklist: "enable"
      options: "block-invalid-url"
      ftgd_wf:
        options: "error-allow"
        filters:
          ################################
          ###### Potentially Liable ######
          ################################
          -
          # Drug Abuse
            id: "1"
            category: "1" 
            action: "block"
          -
          # Hacking
            id: "3"
            category: "3" 
            action: "block"
          -
          # Illegal or Unethical
            id: "4"
            category: "4"
            action: "block"
          -
          # Discrimination
            id: "5"
            category: "5"
            action: "block"
          -
          # Explicit Violence
            id: "6"
            category: "6"
            action: "block"
          -
          # Extremist Groups
            id: "12"
            category: "12"
            action: "block"
          - 
          # Proxy Avoidance
            id: "59"
            category: "59"
            action: "monitor"
          - 
          # Plagiarism
            id: "62"
            category: "62"
            action: "monitor"
          - 
          # Child Sexual Abuse
            id: "83"
            category: "83"
            action: "block"
          - 
          # Terrorism
            id: "96"
            category: "96"
            action: "block"
          -
          # Crypto Mining
            id: "98"
            category: "98" 
            action: "block"
          - 
          # Potentially Unwanted Program
            id: "99"
            category: "99"
            action: "block"
          
          ##################################
          ###### Adult/Mature Content ######
          ##################################
          -
          # Alternative Beliefs
            id: "2"
            category: "2" 
            action: "monitor"
          -
          # Abortion
            id: "7"
            category: "7"
            action: "monitor"
          -
          # Other Adult Materials
            id: "8"
            category: "8"
            action: "monitor"
          -
          # Advocacy Organizations
            id: "9"
            category: "9"
            action: "monitor"              
          -
          # Gambling
            id: "11"
            category: "11"
            action: "block"
          -
          # Nudity and Risque
            id: "13"
            category: "13"
            action: "block"
          -
          # Pornography
            id: "14"
            category: "14"
            action: "block"
          -
          # Dating
            id: "15"
            category: "15"
            action: "monitor"
          -
          # Weapons (Sales)
            id: "16"
            category: "16"
            action: "block"
          - 
          # Marijuana
            id: "57"
            category: "57"
            action: "block"
          - 
          # Sex Education
            id: "63"
            category: "63"
            action: "block"
          - 
          # Alcohol
            id: "64"
            category: "64"
            action: "block"
          - 
          # Tobacco
            id: "65"
            category: "65"
            action: "block"
          - 
          # Lingerie and Swimsuit
            id: "66"
            category: "66"
            action: "block"
          - 
          # Sports Hunting and War Games
            id: "67"
            category: "67"
            action: "block"

          #################################
          ###### Bandwidth Consuming ######
          #################################
          -
          # Freeware and Software Downloads
            id: "19"
            category: "19"
            action: "monitor"
          -  
          # File Sharing and Storage
            id: "24"
            category: "24"
            action: "monitor"
          - 
          # Streaming Media and Download
            id: "25"
            category: "25"
            action: "monitor"
          -
          # Peer-to-peer File Sharing
            id: "72"
            category: "72"
            action: "block"
          - 
          # Internet Radio and TV
            id: "75"
            category: "75"
            action: "monitor"
          - 
          # Internet Telephony
            id: "76"
            category: "76"
            action: "monitor"
          
          ###########################
          ###### Security Risk ######
          ###########################
          -
          # Malicious Websites
            id: "26"
            category: "26"
            action: "block"
          - 
          # Phishing
            id: "61"
            category: "61"
            action: "block"
          - 
          # Spam URLs
            id: "86"
            category: "86"
            action: "block"
          - 
          # Dynamic DNS
            id: "88"
            category: "88"
            action: "monitor"
          - 
          # Newly Observed Domain
            id: "90"
            category: "90"
            action: "monitor"
          - 
          # Newly Registered Domain
            id: "91"
            category: "91"
            action: "monitor"
          
          #########################################
          ###### General Interest - Personal ######
          #########################################
          -
          # Advertising
            id: "17"
            category: "17"
            action: "monitor"
          -
          # Brokerage and Trading
            id: "18"
            category: "18"
            action: "monitor"
          -
          # Games
            id: "20"
            category: "20"
            action: "monitor"              
          -
          # Web-based Email
            id: "23"
            category: "23"
            action: "monitor"
          - 
          # Entertainment
            id: "28"
            category: "28"
            action: "monitor"
          - 
          # Arts and Culture
            id: "29"
            category: "29"
            action: "monitor"
          - 
          # Education
            id: "30"
            category: "30"
            action: "monitor"
          - 
          # Health and Wellness
            id: "33"
            category: "33"
            action: "monitor"
          - 
          # Job Search
            id: "34"
            category: "34"
            action: "monitor"
          - 
          # Medicine
            id: "35"
            category: "35"
            action: "monitor"
          - 
          # News and Media
            id: "36"
            category: "36"
            action: "monitor"
          - 
          # Social Networking
            id: "37"
            category: "37"
            action: "monitor"
          - 
          # Political Organizations
            id: "38"
            category: "38"
            action: "monitor"
          - 
          # Reference
            id: "39"
            category: "39"
            action: "monitor"
          - 
          # Global Religion
            id: "40"
            category: "40"
            action: "monitor"
          - 
          # Shopping
            id: "42"
            category: "42"
            action: "monitor"
          - 
          # Society and lifestyles
            id: "44"
            category: "44"
            action: "monitor"
          - 
          # Sports
            id: "46"
            category: "46"
            action: "monitor"
          - 
          # Travel
            id: "47"
            category: "47"
            action: "monitor"
          - 
          # Personal Vehicles
            id: "48"
            category: "48"
            action: "monitor"
          - 
          # Dynamic Content
            id: "54"
            category: "54"
            action: "monitor"
          - 
          # Meaningless Content
            id: "55"
            category: "55"
            action: "monitor"
          - 
          # Folklore
            id: "58"
            category: "58"
            action: "monitor"
          - 
          # Web Chat
            id: "68"
            category: "68"
            action: "monitor"
          - 
          # Instant Messaging
            id: "69"
            category: "69"
            action: "monitor"
          - 
          # Newsgroups and Message Boards
            id: "70"
            category: "70"
            action: "monitor"
          - 
          # Digital Postcards
            id: "71"
            category: "71"
            action: "monitor"
          - 
          # Child Education
            id: "77"
            category: "77"
            action: "monitor"
          - 
          # Real Estate
            id: "78"
            category: "78"
            action: "monitor"
          - 
          # Restaurant and Dining
            id: "79"
            category: "79"
            action: "monitor"
          -
          # Personal Websites and Blogs
            id: "80"
            category: "80"
            action: "monitor"
          - 
          # Content Servers
            id: "82"
            category: "82"
            action: "monitor"
          - 
          # Domain Parking
            id: "85"
            category: "85"
            action: "monitor"
          - 
          # Personal Privacy
            id: "87"
            category: "87"
            action: "monitor"
          - 
          # Auction
            id: "89"
            category: "89"
            action: "monitor"
          
          #########################################
          ###### General Interest - Business ######
          #########################################
          -
          # Finance and Banking
            id: "31"
            category: "31"
            action: "monitor"
          - 
          # Search Engines and Portals
            id: "41"
            category: "41"
            action: "monitor"
          - 
          # General Organizations
            id: "43"
            category: "43"
            action: "monitor"
          - 
          # Business
            id: "49"
            category: "49"
            action: "monitor"
          - 
          # Information and Computer Security
            id: "50"
            category: "50"
            action: "monitor"
          - 
          # Government and Legal Organizations
            id: "51"
            category: "51"
            action: "monitor"
          - 
          # Information Technology
            id: "52"
            category: "52"
            action: "monitor"
          - 
          # Armed Forces
            id: "53"
            category: "53"
            action: "monitor"
          - 
          # Web Hosting
            id: "56"
            category: "56"
            action: "monitor"
          - 
          # Secure Websites
            id: "81"
            category: "81"
            action: "monitor"
          - 
          # Web-based Applications
            id: "84"
            category: "84"
            action: "monitor"
          - 
          # Charitable Organizations
            id: "92"
            category: "92"
            action: "monitor"
          - 
          # Remote Access
            id: "93"
            category: "93"
            action: "monitor" 
          - 
          # Web Analytics
            id: "94"
            category: "94"
            action: "monitor"
          - 
          # Online Meeting
            id: "95"
            category: "95"
            action: "monitor"
          - 
          # URL Shortening
            id: "97"
            category: "97"
            action: "monitor"
          - 
          # Artificial Intelligence Technology
            id: "101"
            category: "101"
            action: "monitor"
          -
          # Cryptocurrency
            id: "100"
            category: "100"
            action: "monitor"
          
          ##############################
          ###### Local Categories ######
          ##############################
          -
          # custom1
            id: "140"
            category: "140"
            action: "monitor"
          -
          # custom2
            id: "141"
            category: "141"
            action: "block"
          -
          # Allowed
            id: "190"
            category: "190"
            action: "monitor"
          -
          # Blocked
            id: "191"
            category: "191"
            action: "block"

          ##############################
          ######     Unrated      ######
          ##############################
          -
          # Unrated
            id: "102"
            category: "0"
            action: "monitor"

# - name: Prepare shell script to enable the webfilter in the GUI
#   raw: |
#         cat > {{script_path }} << EOF_OUTER
#         # /bin/bash
#         # Please make sure tool sshpass is installed. e.g. on Debian/Ubuntu, apt-get install sshpass.
#         # Optionally you can pass some parameters.
#         # The character `a` at second line below is to avoid post-login-banner barrier.
#         sshpass -p '{{ fgt_pass }}' ssh -o StrictHostKeyChecking=no {{ fgt_user }}@{{ ansible_host }} <<EOF
#         a
#         # ====================== Edit Your Commands Below =============================================
#         config config webfilter profile
#           edit 'HTMS Webfilter'
#             config ftgd-wf
#               unset options
          
#         end
#         # ==============================================================================================
#         EOF
#         EOF_OUTER


# - name: Enable the webfilter in the GUI
#   raw: |
#         chmod +x {{ script_path }} && {{ script_path }}
#   args:
#     executable: /bin/bash
