- hosts: envwater-comm
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - device_type: "UBNT"
  gather_facts: False

  tasks:
    - name: Gather LLDP Neighbors
      aoscx_facts:
        gather_network_resources:
          - lldp_neighbors
      register: lldp

  

    # - name: Configure ports for Ubiquiti access points
    #   aoscx_l2_interface:
    #     interface: "{{ item.key }}"
    #     vlan_mode: access
    #     vlan_access: 200


    - name: Display Information
      debug:
        msg: "{{ item }}"
      with_dict: "{{ lldp.ansible_facts.ansible_network_resources.lldp_neighbors | json_query('*.chassis_name') }}"
      # when: device_type in item.value