- hosts: access_switches
  collections:
    - arubanetworks.aoscx

  tasks:
    - name: Configure Interfaces 1/1/1-48
      aoscx_l2_interface:
        interface: 1/1/{{ item }}
        vlan_mode: trunk
        vlan_trunks:
          - 2
          - 3
        native_vlan_id: 2
        # port_security_enable: False
        # port_security_client_limit: 3
        # port_security_violation_action: shutdown
        # port_security_recovery_time: 60
      loop: "{{ query('sequence', 'start=1 end=48') }}"

    - name: Configure Interfaces 2/1/1-48
      aoscx_l2_interface:
        interface: 2/1/{{ item }}
        vlan_mode: trunk
        vlan_trunks:
          - 2
          - 3
        native_vlan_id: 2
        # port_security_enable: False
        # port_security_client_limit: 3
        # port_security_violation_action: shutdown
        # port_security_recovery_time: 60
      loop: "{{ query('sequence', 'start=1 end=48') }}"
      when:
        - stack_members is defined
        - stack_members == 2 or stack_members == 3

    - name: Configure Interfaces 3/1/1-48
      aoscx_l2_interface:
        interface: 3/1/{{ item }}
        vlan_mode: trunk
        vlan_trunks:
          - 2
          - 3
        native_vlan_id: 2
        # port_security_enable: False
        # port_security_client_limit: 3
        # port_security_violation_action: shutdown
        # port_security_recovery_time: 60
      loop: "{{ query('sequence', 'start=1 end=48') }}"
      when:
        - stack_members is defined
        - stack_members == 3  