- hosts: core_switches
  collections:
    - arubanetworks.aoscx
  vars_files:
    - network_settings.yml
  
  tasks:
    - name: Create VLAN Interface SVI with IP Helper
      aoscx_vlan_interface:
        vlan_id: "{{ item.vlan }}"
        description: "{{ item.description }}"
        ipv4:
          - "{{ item.ipv4 }}"
        ip_helper_address:
          - "{{ item.ip_helper }}"
        state: create
      with_list: "{{ vlans }}"
      when: 
        - item.ipv4 is defined
        - item.ip_helper is defined

    - name: Create VLAN Interface SVI without IP Helper
      aoscx_vlan_interface:
        vlan_id: "{{ item.vlan }}"
        description: "{{ item.description }}"
        ipv4:
          - "{{ item.ipv4 }}"
        state: create
      with_list: "{{ vlans }}"
      when: 
        - item.ipv4 is defined
        - item.ip_helper is undefined

