- hosts: access_switches
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Clear Interfaces 1/1/1-48
      aoscx_command:
        commands:
          - configure terminal
          - default interface 1/1/1-1/1/48

    - name: Configure Interfaces 2/1/1-48
      aoscx_command:
        commands:
          - configure terminal
          - default interface 2/1/1-2/1/48
      when:
        - stack_members is defined
        - stack_members == 2 or stack_members == 3

    - name: Configure Interfaces 3/1/1-48
      aoscx_command:
        commands:
          - configure terminal
          - default interface 3/1/1-3/1/48
      when:
        - stack_members is defined
        - stack_members == 3  