---

- name: Getting the IP range for SSLVPN_TUNNEL_ADDR1
  fortinet.fortios.fortios_configuration_fact:
    vdom: "{{ vdom }}"
    selector: 'firewall_address'
    filters:
      - name=="SSLVPN_TUNNEL_ADDR1"
  register: address_object

- name: Creating the IPSEC_TUNNEL_ADDR1 address object
  fortios_firewall_address:
    vdom: "{{ vdom }}"
    state: present
    firewall_address:
      name: "IPSEC_TUNNEL_ADDR1"
      type: "iprange"
      start_ip: "{{ address_object.meta.results.0['start-ip'] }}"
      end_ip: "{{ address_object.meta.results.0['end-ip'] }}"