- name: Loop Test
  hosts: localhost
  gather_facts: True


  tasks:
  - name: Import CSV File
    read_csv:
      path: access_points.csv
    register: access_points
  
  - debug:
      msg: "The Meraki {{ item.model }} with serial number {{ item.serial }} has a hostname of {{ item.hostname }}."
    loop: "{{ access_points.list }}"

