---
- name: Meraki API Commands
  gather_facts: false
  connection: local
  hosts: localhost
  vars:
    device_type: "MS120-8LP"
  vars_files:
    - vars/external_vars.yml
  
    
  tasks:

    - name: Gather Devices
      meraki_device:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        state: query
      register: my_devices
      tags: gather

    - name: Debug Output
      debug:
        msg: "{{ item.model }}"
      loop: "{{ my_devices.data | list }}"

    - name: Save output to a file
      copy:
        content: "{{ my_devices.data | to_nice_json }}"
        dest: "meraki_devices.json"
      tags: savefile
