---
# This Playbook is used to import devices into the Meraki Dashboard. You can change the path to your own CSV file and use the access_points.csv for the format.
- name: Meraki Wireless Deployment
  hosts: localhost
  gather_facts: True
  vars_files:
    - vars/external_vars.yml

  tasks:
  - name: Import CSV File
    read_csv:
      path: access_points.csv
    register: devices
  
  #- debug: ansible 
  #    msg: "{{ item.hostname }} , {{ item.serial }}"
  #  loop: "{{ devices.list }}"
 

  - name: Add devices to Network
    meraki_device:
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_id: "{{ net_id }}"
      state: present
      serial: "{{ item.serial }}"
    loop: "{{ devices.list }}"


  - name: Update device Information
    meraki_device:
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_id: "{{ net_id }}"
      state: present
      serial: "{{ item.serial }}"
      name: " {{ item.hostname }}"
      address: "{{ item.address }}"
      move_map_marker: yes
    loop: "{{ devices.list }}"