---
# This script is for deploying a Meraki Combined Network with Wireless using 802.1x.
# You will have have to provide the auth_key and org_name from the Meraki Dashboard.
# Documentation for enabling API access can be found at https://documentation.meraki.com/General_Administration/Other_Topics/Cisco_Meraki_Dashboard_API
- name: Meraki Deployment
  hosts: localhost
  vars:
    auth_key: "{{ auth }}"
    org_name: "{{ org }}"
    address: " "
    
  tasks:
# Access points are defined in YAML format in the access_points.yaml file located in the same directory. You will have to provide your own serial numbers.
    - name: include variables for devices
      include_vars:
        file: access_points.yaml
        name: devices

    - name: Create site network
      meraki_network:
        auth_key: "{{ auth_key }}"
        state: present
        org_name: "{{ org_name }}"
        name: "{{ item.value.network_name }}"
        type:
          - wireless
        timezone: "America/Chicago"
      register: off_network
      with_dict: "{{ devices }}"
      when: "'device-1' in item.key"

    - name: Add devices to Network
      meraki_device:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        net_id: "{{ off_network.results.0.data.id }}"
        state: present
        serial: "{{ item.value.serial_no }}"
      register: off_add_dev1nan
      with_dict: "{{ devices }}"

    - name: Update device Information
      meraki_device:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        net_id: "{{ off_network.results.0.data.id }}"
        state: present
        serial: "{{ item.value.serial_no }}"
        name: " {{ item.value.device_name }}"
        address: "{{ address }}"
        move_map_marker: yes
      register: off_update_dev1
      with_dict: "{{ devices }}"

    - name: Create SSID
      meraki_ssid:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        net_id: "{{ off_network.results.0.data.id }}"
        state: present
        name: Ansible-Wifi
        auth_mode: 8021x-radius
        radius_servers:
          - host: 
            port: 1812
            secret: 
          - host: 
            port: 1812
            secret: 
        enabled: yes
        ip_assignment_mode: "Bridge mode"
        use_vlan_tagging: yes
        default_vlan_id: 20
        min_bitrate: 12


        

      
      