---
- name: Meraki API Commands
  gather_facts: false
  connection: local
  hosts: localhost
  vars_files:
    - vars/external_vars.yml

  tasks:
  - name: Add devices to Network
    meraki_network:
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "Ansible-Wireless"
      state: present