---
- name: Meraki Organizations
  gather_facts: false
  connection: local
  hosts: localhost
  vars_files:
    - vars/external_vars.yml
  
  tasks:

    - name: Gather Devices
      meraki_organization:
        auth_key: "{{ auth_key }}"
        state: query
      register: my_orgs
      tags: gather

    - name: Save output to a file
      copy:
        content: "{{ my_orgs.data | to_nice_json }}"
        dest: "meraki_organizations.json"
      tags: savefile
